name: Spring Boot Postgres Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run_test:
    name: Unit Test
    runs-on: ubuntu-18.04
    steps:
      - run: echo "Starting execute unit test"
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Maven Verify
        run: mvn clean verify

  build:
    name: Build
    runs-on: ubuntu-18.04
    needs: run_test
    steps:
      - run: echo "Starting build package"
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Maven Build
        run: mvn clean package -Dmaven.test.skip=true
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: hendrojun/springboot-postgres:latest
  deployment:
    name: Deploy container using SSH
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - run: echo "Starting deploy container"
      - uses: actions/checkout@v3
      - name: Copy environment file via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          port: 22
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: .dev.env
          target: /home/${{ secrets.EC2_SSH_USERNAME }}
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          port: 22
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            docker stop springboot-postgres
            docker rmi hendrojun/springboot-postgres:latest
            docker pull hendrojun/springboot-postgres:latest
            docker run -d --rm --name springboot-postgres -p 80:8080 -p 443:8080 --env-file=.dev.env --network kampus_merdeka hendrojun/springboot-postgres:latest
